### PR TITLE
chore: remove empty files, clean up ignore files, remove extra lines in README

### PR DESCRIPTION
**Pull request by uncenter**
:)

https://github.com/PatrickJS/node-everything/commit/9c5c9266753b3b476c39f4dced99a8620fc2ad3d most of this is self inflicted bloat lol

### CODE REVIEW

**Comment by PatrickJS** [comment]
I think I need these config files to feel like I'm using _Modern_ **JavaScript**

**Comment by uncenter** [comment]
I can't create an issue about the 10mb problem since I think you have issues disabled, but what you could do is do something funky with a `postinstall` script or something?

**Comment by PatrickJS** [comment]
yeah I was thinking a preinstall then inject it haha

**Comment by PatrickJS** [comment]
but people shouldn't install it. I think it might make more sense to list out the most common packages within the limit and only publish that. but will need ways to figure all that out

**Comment by uncenter** [comment]
What's the script you are using rn to get the packages?

**Comment by PatrickJS** [comment]
I forgot how I did it 8 years ago but I used [`all-the-package-names`](https://github.com/nice-registry/all-the-package-names) for latest

**Comment by PatrickJS** [comment]
if you're down to help figure out how we all can legit install everything _at home_ then I don't mind adding you to the repo and package etc or maybe we can give this to [jsDelivr](https://github.com/jsdelivr) to figure it out

**Comment by PatrickJS** [comment]
it might make sense just moving this into https://github.com/nice-registry and work with them on figuring out the best way to get the top used packages that fits within 10mb compressed package.json I think it might even be useful 😂

**Comment by uncenter** [comment]
I'd love to help out. How about we split it up? Into a bunch of different packages?

**Comment by PatrickJS** [comment]
oh you're smart asf haha that's actually the best way to go

**Comment by uncenter** [comment]
Say each package gets a few hundred thousand packages or whatever the limit is, and the main `everything` package depends on all of those sub packages!

**Comment by PatrickJS** [comment]
yeah thats smart asf. we can just be dumb about it and split every 1k packages or something. So we need to figure out the best way to split up everything and create each sub package

**Comment by uncenter** [comment]
There are `2,597,438` lines.
The file is roughly `66mb`, or `66,000,000b`.

`66,000,000/2,597,438` is roughly `25b` per line on average.

`10mb` is `10,000,000b`, and `10,000,000/25` is `400,000`. So I think we can fit about 400k lines per sub-package, which is ~6.5 packages to hold all 2.5m lines, round that up to 7.

**Comment by PatrickJS** [comment]
well package.json is 83mb right now uncompressed so if we just be dumb about it and split it into everything-a and everything-b then we can publish it then figure out a better way. I think it would make more sense creating a package for every scope packages in and then everything else will just be packaged by their first letter group haha

**Comment by uncenter** [comment]
That works too! `everything-a`, `everything-b`, ..., `everything-other` (for symbols), `everything-number`. All of those names aren't taken.

**Comment by PatrickJS** [comment]
lets continue this on twitter DM

**Comment by uncenter** [comment]
:eyes: good to merge?

**Pull request merged**
